[build]
builder = "NIXPACKS"
buildCommand = "cd Backend/Backend && dotnet publish -c Release -o out"

[deploy]
startCommand = "cd Backend/Backend/out && dotnet Backend.dll"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
